import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
chapters=[
('roads','01','Read the road','Lanes, cycle paths & the places you drive.','motorway-exit.webp',[1,2,3,4,5,6]),
('people','02','People come first','Spot the people who need extra space.','child-cyclist.webp',[7,8]),
('car','03','Know your car','Weight, passengers, lights & equipment.','tunnel.webp',[9,10,11]),
('speed','04','Speed & stopping','Choose a safe speed. Leave room to react.','school-zone.webp',[12,13]),
('passing','05','Passing & overtaking','When to pass, and when to wait.','passing-cyclist.webp',[14,15,16]),
('priority','06','Who goes first?','Junctions, signals, turns & public transport.','priority-from-right.webp',[17,18,19,20,21,22]),
('direction','07','Choose your direction','Read restrictions, arrows & exceptions.','mandatory-straight.webp',[23,24]),
('parking','08','Stop & park','Find a legal space and decode the signs.','parking-disc.webp',[25,26,27]),
('safety','09','Stay safe','Fitness, emergencies & a healthy car.','reflective-vest.webp',[28,29,30,31])]
C=[dict(id=a,number=b,title=c,description=d,image=e,lessons=f) for a,b,c,d,e,f in chapters]
L=[]
def card(title,intro,facts,remember,more='',image=None):
 return dict(title=title,intro=intro,facts=facts,remember=remember,more=more,image=image)
def lesson(n,title,pages,cards,source='code'):
 chapter=next(c['id'] for c in C if n in c['lessons'])
 L.append(dict(id=n,chapter=chapter,title=title,pages=pages,cards=cards,source=source,minutes=5))
lesson(1,'The public road',[1,8],[
card('See the whole road','The public road is more than the part cars drive on. It can include the carriageway, cycle paths, pavements and verges.', ['The carriageway is the part normally used by vehicles. A lane is a marked strip within it.','A pavement is for pedestrians. A marked cycle path is reserved for the users allowed on it.','Road rules can apply on a privately owned road when it is open to public traffic. Ownership alone does not decide.'],'Carriageway ≠ the entire public road.',image='road-anatomy.webp'),
card('Keep right, look ahead','On an ordinary road, drive as close to the right-hand edge of the carriageway as appropriate.', ['Allow safe space beside parked vehicles and vulnerable users. Keeping right does not mean squeezing past a cyclist.','Use mirrors and check blind spots before changing your position.','Approach bends and crests at a speed that lets you stop within the distance you can see.'],'Your lane position should leave you room to react.','Lane-choice exceptions exist on one-way roads and, in built-up areas, on roads with at least two lanes in your direction. Signs and lane arrows still govern.',image='public-road.webp'),
card('Read signs in layers','First recognise the sign family, then read its symbol and any supplementary plate.', ['A red-bordered triangle usually warns of a hazard. A red-bordered circle usually restricts you.','Blue circles usually give mandatory instructions. Rectangular signs give information or zone rules.','STOP is an octagon; give way is an inverted triangle. Their shapes help you recognise them even from behind.'],'Shape first. Symbol second. Extra plate third.','A zone rule continues throughout the zone until its end sign; do not assume a junction cancels it.',image='yield-sign.webp')])
lesson(2,'Lanes & road markings',[9,17],[
card('Solid or broken?','Road markings tell you where you may move. Treat each line as a decision, not decoration.', ['Do not cross a continuous white line or drive astride it. A broken white line may be crossed when safe.','With a solid and broken line side by side, obey the line closest to you.','Temporary orange markings take precedence over ordinary white markings in roadworks.'],'The line nearest you controls your move.',image='lane-markings.webp'),
card('Merge like a zipper','When traffic is moving very slowly and a lane ends or is blocked, use alternating merging immediately before the narrowing.', ['Continue in your lane until the merge point. Do not force an early merge far back in the queue.','Drivers in the continuing lane let one vehicle from the ending lane enter, then continue in turn.','When lanes on both sides end, the continuing lane first admits one from the right and then one from the left.'],'Very slow traffic + lane reduction = take turns at the pinch point.','Zipper merging does not give normal motorway entering traffic priority over vehicles already on the motorway.',image='zipper-merge.webp'),
card('Arrows, islands & reserved lanes','Get into the correct lane in good time. A painted route can be just as important as a roadside sign.', ['Follow the directions shown by lane arrows at the junction.','Do not drive, stop or park on hatched areas or traffic islands.','A bus lane or special reserved track is not an extra lane for a car. Only enter where the specific rules allow it, such as permitted positioning before a turn.'],'Never use the hatched area as a shortcut.',image='motorway-exit.webp')])
lesson(3,'Cycle paths & cycle zones',[18,25],[
card('A cycle path is a space, not a colour','Two parallel broken white lines or a mandatory path sign can identify a cycle path. Red paint by itself is not the legal definition.', ['A suggested cycle strip is part of the carriageway; it is different from a reserved cycle path.','Cross a cycle path carefully to turn or access a property, giving way to its users.','Never stop or park on a cycle path, even briefly to drop someone off.'],'Look for markings and signs, not just red surfacing.',image='shared-cycle-pedestrian-sign.webp'),
card('In a cycle zone, be a guest','A cycle zone has a maximum speed of 30 km/h. Motor vehicles may enter when otherwise permitted, but may not overtake cyclists.', ['Cyclists can use the whole width of a one-way carriageway, or the right-hand half on a two-way road.','The zone continues until its end sign, including across junctions.','Leave space and follow patiently. A cyclist riding centrally is not an invitation to squeeze past.'],'30 km/h. Stay behind the cyclist.','Current wording is “cycle zone” (fietszone). The book’s statement that a bicycle street automatically ends at the next junction is outdated.',image='child-cyclist.webp'),
card('A cycle crossing is not a zebra crossing','A cyclist approaching a separate cycle crossing does not automatically have the same priority as a pedestrian at a zebra crossing.', ['Approach with care and reduce speed. Do not endanger someone already crossing.','A cyclist crossing must take account of approaching traffic and obey signals or priority signs.','When you turn across a cycle path on the road you are leaving or joining, you must give way to its users.'],'Check the type of crossing and the manoeuvre you are making.','Never read this distinction as permission to drive at a cyclist. You always need enough space and time to avoid a collision.')])
lesson(4,'Motorways',[26,37],[
card('Enter smoothly, exit early','Use the acceleration lane to match traffic speed and find a safe gap. Vehicles already on the motorway have priority.', ['The normal maximum for a passenger car is 120 km/h unless a lower limit applies.','A vehicle must be capable of reaching 70 km/h on level ground to be admitted. This is not a minimum you must maintain in congestion.','No pedestrians, cyclists, mopeds or agricultural vehicles. Never reverse, turn around or use the median.'],'An entry lane helps you join; it does not give you priority.',image='motorway-hard-shoulder.webp'),
card('The hard shoulder is for emergencies','A missed exit is inconvenient. A sudden swerve, reverse or stop is dangerous.', ['Continue to the next exit if you miss yours. Never reverse back.','Do not drive or stop on the hard shoulder except for a genuine emergency or an explicitly opened rush-hour lane.','If you break down, use hazard lights, stop as far right as possible, put on a reflective vest and get behind the barrier when safe.'],'Missed your exit? Take the next one.',image='motorway-exit.webp'),
card('Make the rescue corridor early','When a queue forms on a road with at least two lanes in your direction, create space for emergency vehicles before they arrive.', ['Traffic in the far-left lane moves left. Every other lane moves right.','Keep the corridor open between the leftmost lane and the lane beside it.','Do not follow an emergency vehicle through the corridor. It is not a passing lane.'],'Left lane left. All others right.','Move within the available safe space; the obligation does not authorise endangering people or treating the hard shoulder as an ordinary lane.',image='rescue-corridor.webp')])
lesson(5,'Road types & speed defaults',[38,43],[
card('Recognise the road you are on','A motorway and a motor road have different access signs. A motor-road sign does not, by itself, make the limit 120 km/h.', ['Motorways and motor roads exclude pedestrians and cyclists.','On a road with at least two lanes in each direction separated by a physical central reservation, the normal car maximum is 120 km/h unless signs lower it.','A painted central strip is not a physical reservation.'],'Identify the road layout before choosing the default limit.',image='temporary-road-markings.webp'),
card('An ordinary road outside town','For a passenger car on an ordinary road outside a built-up area, the regional default matters.', ['Flanders: normally 70 km/h.','Wallonia: normally 90 km/h. Brussels: normally 70 km/h outside built-up areas, and 30 km/h inside them.','Posted limits and road-layout exceptions take precedence. On a Flemish road with two or more lanes each way but only painted separation, the default is still 70 km/h.'],'For your Flemish exam: ordinary road outside town = 70.','A lower sign, a zone, vehicle restrictions and conditions can all require a lower speed. Never infer 90 just because a road is wide.'),
card('Signs beat assumptions','Speed restrictions can apply to a short stretch, a whole zone or specific vehicles.', ['A circular speed-limit sign usually applies from the sign until the next junction, unless replaced, ended or governed by a different provision.','A speed-zone sign applies throughout the zone until the end-zone sign.','A built-up-area boundary changes the general default; a different posted limit can apply.'],'A junction does not cancel a zone.',image='school-zone.webp')])
lesson(6,'Special places',[44,56],[
card('In town, expect people','The built-up-area sign defines the legal boundary. Buildings alone do not tell you the speed limit.', ['Flanders and Wallonia: the normal built-up-area car limit is 50 km/h.','Brussels: normally 30 km/h unless a sign permits another speed.','A signed school zone is 30 km/h. Respect active variable signs and the indicated zone boundaries.'],'In Flanders, 50 in town; 30 in a signed zone.',image='school-zone.webp'),
card('Residential areas: walking pace matters','In a signed residential or home zone (woonerven / erven), pedestrians may use the full width of the road.', ['The maximum is 20 km/h. Children may play in the street.','Do not endanger or obstruct pedestrians; stop if necessary.','Park only in spaces indicated by markings or signs.'],'20 km/h, pedestrians throughout, marked parking only.',image='speed-20.webp'),
card('Play streets & pedestrian areas','Some streets are temporarily or permanently reserved for people, with limited vehicle access.', ['A play street is closed to ordinary through traffic during the hours shown. Permitted drivers travel at walking pace and give pedestrians priority.','Pedestrian areas admit only specifically allowed vehicles or users at indicated times. Do not assume living nearby grants every access right.','Read supplementary plates for time windows, delivery access and local exceptions.'],'The plate tells you who may enter, and when.','A sign allowing local traffic is a restriction on through traffic, not an exemption from other speed or priority rules.')])
lesson(7,'Pedestrians',[57,62],[
card('At a zebra crossing, prepare to stop','Approach an unsignalised pedestrian crossing at a moderate speed. Give way to people on it or about to step onto it.', ['A pedestrian clearly preparing to cross does not need to step into your lane first.','Never pass a vehicle approaching or stopped at an unsignalised pedestrian crossing. It may be hiding someone.','Keep crossings clear in a queue. Do not stop on the stripes.'],'Slow down before the crossing, not on it.','Signals govern a controlled crossing, but a green light does not let you endanger pedestrians finishing their crossing.'),
card('When you turn, people continue','Turning changes your route. It does not erase a pedestrian’s route along the road.', ['Give way to pedestrians crossing the carriageway you are turning into.','Give way to pedestrians crossing the road you are leaving, as required when turning.','Check beside you and behind you for cyclists before crossing their path.'],'Before turning: mirrors, blind spot, crossing users.'),
card('Give vulnerable people more room','Children, older people and people with reduced mobility may move or react unpredictably.', ['Slow down and be ready to stop near schools, buses, parked cars and groups of children.','Leave at least 1 metre when passing a pedestrian on the carriageway in a built-up area; outside it, at least 1.5 metres.','Do not open a car door into the path of a pedestrian or cyclist. Check first.'],'A small speed reduction buys a lot of reaction time.',image='child-cyclist.webp')])
lesson(8,'Drivers & attention',[63,65],[
card('Who is a driver?','“Driver” is broader than someone in a car. A cyclist, a rider and someone leading animals can be drivers too.', ['Priority from the right applies to drivers, including cyclists, unless a different rule applies.','Someone pushing a bicycle or two-wheeled moped is treated as a pedestrian.','Vehicle-category signs can apply to a car, a motorcycle or a cycle differently. Read the symbol.'],'A cyclist can have the same priority as a car.'),
card('Keep the phone out of your hands','While driving, you may not use, hold or manipulate a mobile electronic device with a screen unless it is secured in a suitable holder.', ['A red light or a traffic queue is still part of driving, not a parking break.','Set navigation before moving. A holder does not make distracting use safe.','Stop and park legally before handling your phone.'],'Red light = still driving.','This current wording is broader than the book’s older “mobile phone” language: it covers mobile devices with a screen.'),
card('Small wheels, real road users','Electric scooters are generally treated like bicycles under the current rules. Be ready to give their riders the same priority and safe space.', ['Motorised mobility devices generally follow cyclist rules, rather than riding on pavements. Mobility-aid exceptions exist.','Normal electric scooters have a maximum design speed of 25 km/h. Riders generally need to be at least 16, with limited exceptions.','Since 1 September 2026, a helmet is required on motorised mobility devices whose design speed is above 20 km/h.'],'A scooter can be a cyclist in the rules, and easy to miss in a blind spot.','The helmet can be an approved moped helmet or a cycle helmet protecting the temples and back of the head. Treat the design-speed threshold separately from the speed at which someone is currently riding.')])
lesson(9,'Licence B, weight & equipment',[66,72],[
card('Maximum authorised mass is a limit','Maximum authorised mass (MAM; Dutch MTM) is the permitted loaded mass. Actual mass is what the vehicle weighs right now.', ['A standard category B licence generally covers vehicles up to 3,500 kg MAM and no more than 8 passenger seats in addition to the driver.','Use the vehicle documents for its limits. An empty heavy vehicle does not become a category B vehicle just because its current mass is lower.','Passengers, fuel and luggage all contribute to actual mass. Do not overload.'],'Licence categories use authorised mass, not an empty-day weigh-in.'),
card('Towing with a full B licence','Two standard B cases are worth remembering.', ['A trailer of up to 750 kg MAM may be towed by an eligible category B vehicle.','A trailer above 750 kg MAM can be within ordinary B if the combination’s total MAM is no more than 3,500 kg.','A B code 96 or BE entitlement can be needed for heavier combinations. Always respect the vehicle’s technical towing limit.'],'Trailer ≤750, or heavier trailer with combination ≤3,500.','A provisional B licence does not permit towing a trailer. Extra entitlements and limited special vehicle exceptions require their own official checks.'),
card('Have the essentials ready','For a normal Belgian-registered car, keep the required equipment and documents available.', ['Equipment: warning triangle, first-aid kit and approved fire extinguisher. Keep a reflective vest reachable for motorway breakdowns.','Documents include your driving licence, registration and insurance certificate; the conformity and inspection documents must be available where required.','Check the spare-wheel or repair-kit instructions before you need them.'],'A vest buried under luggage is hard to use safely.',image='reflective-vest.webp')],source='licence')
lesson(10,'Passengers & loads',[73,79],[
card('Every passenger needs a safe seat','Seat belts protect the driver and passengers in front and rear seats.', ['Wear the belt correctly across the shoulder and low over the hips, not under the arm.','A child under 18 who is shorter than 1.35 m normally needs a suitable child restraint.','Never use a rear-facing child seat in front of an active frontal airbag. Deactivate the airbag or use a suitable rear seat.'],'Under 1.35 m: use the right child restraint.','There are narrow legal exceptions for certain transport situations. Plan normal car journeys using an appropriate restraint rather than relying on an exception.'),
card('Secure the load','Your load must not fall, drag, obstruct your view or endanger other road users.', ['Keep number plates, lights and indicators visible. Secure loose objects inside the car too.','For a normal car, the usual maximum loaded width is 2.55 m and height is 4 m; posted smaller clearance limits still apply.','Do not exceed the vehicle’s permitted mass, roof-load limit or towing limit.'],'Heavy objects low, secured, and within the limits.'),
card('What may project?','A passenger-car load must not project beyond the front. Rear projection has specific limits and marking rules.', ['The normal maximum rear projection is 1 metre.','An indivisible load may extend up to 3 metres at the rear under the applicable marking requirements.','When rear projection exceeds 1 metre, use the prescribed 50 × 50 cm red-and-white warning panel; additional light and reflectors are needed when lighting is required.'],'No front projection. Check rear distance and marking.','Do not confuse a warning panel for a projecting load with the warning triangle used for a breakdown. If the transport is unusual, verify Article 46 before departure.')])
lesson(11,'Lights & the horn',[80,85],[
card('Use lights to see and be seen','Use dipped headlights after dark, in tunnels and when visibility conditions require them.', ['Dipped beams and rear position lights are required between nightfall and daybreak and when you cannot see clearly for about 200 metres.','High beam must not dazzle oncoming road users or the driver ahead. Switch to dipped beam in time.','Daytime running lights may leave rear lights off; do not rely on them in a dark tunnel or poor visibility.'],'DRLs are not a substitute for proper night lighting.',image='tunnel.webp'),
card('Fog lights have a job','Bright fog lights can dazzle when used unnecessarily.', ['Rear fog lights must be used in fog or snowfall when visibility is below 100 metres, and in heavy rain.','Front fog lights may be used in fog, snowfall or heavy rain.','Switch fog lights off when the conditions no longer justify them.'],'Rear: fog/snow under 100 m, or heavy rain.','Hazard lights signal danger or a breakdown. They do not make illegal parking legal.'),
card('Signal early, without misleading','Indicators inform other road users of your intended move. They do not give you priority.', ['Indicate before turning, changing lanes or making a manoeuvre, after checking it is safe.','Signal right when leaving a roundabout; do not mislead drivers at an earlier exit.','Use the horn only as necessary to avoid danger; outside a built-up area it may also warn a driver you intend to overtake. At night, generally use light signals instead unless danger requires the horn.'],'Signal communicates a plan. It does not reserve a gap.')])
lesson(12,'Speed',[86,97],[
card('Your Flemish speed ladder','For a normal car, learn the usual defaults, then look for exceptions.', ['20 km/h in residential/home zones; 30 km/h in signed 30 zones and cycle zones.','50 km/h in a built-up area in Flanders; 70 km/h on most ordinary roads outside it.','120 km/h on motorways and qualifying roads with a physical central reservation, unless a lower limit is shown.'],'20 • 30 • 50 • 70 • 120. Context chooses the number.','Wallonia generally uses 90 outside town; Brussels uses 30 in built-up areas and normally 70 on ordinary roads outside them. Limits for trailers, special vehicles and some road layouts differ.',image='school-zone.webp'),
card('A limit is a ceiling, not a target','You must adapt speed to visibility, weather, road condition, traffic and the people around you.', ['Be able to stop before a foreseeable obstacle within the distance you can see.','Rain, ice, fog, roadworks and parked cars can require much less than the posted maximum.','Do not obstruct traffic by driving abnormally slowly without a valid reason.'],'Legal maximum and safe speed can be different.'),
card('Watch for exam wording','Speed questions often hide the key information in the road layout or regional location.', ['“Outside a built-up area in Flanders, ordinary two-way road, no signs” points to 70 km/h.','“Two lanes each way separated only by paint” is not the 120 km/h physical-reservation case.','“Cycle zone” means 30 km/h and no overtaking cyclists by motor vehicles.'],'Name the road and region before picking a number.','In the Flemish theory exam, a wrong answer about exceeding a maximum speed limit costs 5 points rather than 1. Slow down and read the scenario carefully.')])
lesson(13,'Stopping distance',[98,101],[
card('Two distances make one stop','Stopping distance is reaction distance plus braking distance.', ['During your reaction time, the car continues moving before braking begins.','Braking distance depends on speed, tyres, grip, brakes and road slope.','Alcohol, fatigue and distraction increase reaction time; wet or icy roads increase braking distance.'],'Reaction + braking = stopping.'),
card('Double speed, much more braking','If grip and braking conditions are the same, doubling speed roughly quadruples braking distance.', ['Reaction distance roughly doubles when speed doubles and reaction time stays the same.','At 50 km/h, you travel about 14 metres in one second; at 100 km/h, about 28 metres.','The book’s stopping-distance tables are illustrative estimates, not guaranteed distances or universal legal formulas.'],'The faster you go, the more space you need.','ABS helps prevent wheel lock and preserve steering; it does not guarantee a shorter stop, especially on loose surfaces.'),
card('Leave a gap you can use','Use a fixed roadside point to check a time gap behind the vehicle ahead.', ['In good conditions, use at least a two-second gap as a practical baseline.','Increase it substantially in rain, darkness, low grip or when following a vehicle that blocks your view.','If someone tailgates you, create more room ahead and avoid sharp braking.'],'Two seconds is a starting point. Bad conditions need more.','The legal obligation is a sufficient safety distance. A simple “speed divided by two” distance is a teaching shortcut, not a guarantee in every situation.')])
lesson(14,'Meeting oncoming traffic',[102,107],[
card('Pass each other on the right','When meeting oncoming traffic, both drivers need enough room.', ['Keep right and leave sufficient lateral clearance. Slow or stop if the road is too narrow.','If an obstacle is on your side, normally yield to oncoming traffic before going around it.','Do not force someone onto a verge or cycle path to make your pass possible.'],'Obstacle on your side? Wait for a safe gap.'),
card('Two narrow-road priority signs','Red and black opposed arrows and a blue rectangle with opposed arrows tell you who goes first at a narrow section.', ['A round red-bordered sign with a red upward arrow tells you to give way to oncoming traffic.','A blue sign with a white upward arrow gives your direction priority over oncoming traffic.','Priority still requires you to avoid a collision if the narrow section is already occupied.'],'A priority sign does not make the road wider.'),
card('Space before speed','A meeting manoeuvre is easier when you anticipate the narrow part early.', ['Check parked cars, buses, cyclists and roadworks ahead.','Do not accelerate into a gap that requires another road user to brake sharply.','Be especially patient around a tram, large vehicle or cyclist with limited room.'],'Make the safe gap before you enter it.')])
lesson(15,'Overtaking safely',[108,114],[
card('Three checks before overtaking','Overtaking is normally on the left. Only start when you can complete the manoeuvre safely.', ['Look ahead: clear view, enough space and no prohibition.','Look behind: nobody has already started overtaking you. Check mirrors and blind spots.','Check the vehicle ahead is not signalling a left turn; return right without cutting it off.'],'See enough. Have room. Check behind.'),
card('Passing a cyclist','Leave a legal minimum lateral clearance, and more if conditions demand it.', ['In a built-up area: at least 1 metre.','Outside a built-up area: at least 1.5 metres.','If you cannot leave enough space without breaking another rule or endangering traffic, stay behind.'],'1 m in town. 1.5 m outside. Wait if there is no room.','The same lateral-clearance thresholds apply when passing pedestrians on the carriageway.',image='passing-cyclist.webp'),
card('Right-side exceptions','Passing a moving vehicle on its right is generally prohibited, but specific situations differ.', ['You may pass a vehicle on the right when it clearly indicates and positions for a left turn, if there is enough lawful space.','Parallel slow-moving queues can progress at different speeds without each movement being an overtaking manoeuvre.','Do not move onto a hard shoulder, cycle path or prohibited area to get around someone.'],'A legal exception is not permission to improvise a new lane.')])
lesson(16,'When overtaking is prohibited',[115,123],[
card('If you cannot see, do not go','Passing becomes dangerous when the unseen space ahead could contain an oncoming vehicle.', ['Do not overtake to the left where you have insufficient visibility, such as a blind bend or crest, unless the lawful road layout makes the manoeuvre safe under the rules.','Never cross a continuous white line to overtake.','An overtaking-prohibited sign applies to the vehicle classes and manoeuvres it specifies.'],'A clear view is part of permission.'),
card('Crossings hide people','A stopped vehicle can screen a pedestrian or cyclist.', ['Do not overtake a vehicle approaching or stopped at an unsignalised pedestrian crossing or cycle crossing.','Never overtake on a railway crossing without barriers or traffic lights, apart from the specific narrow exceptions in the code.','Do not overtake at a junction where you must give way under the relevant priority rules.'],'When a car stops at a crossing, expect someone you cannot see.','Junction and level-crossing rules have specific exceptions, for example some two-wheeled vehicles. For a normal car scenario, do not assume you qualify.'),
card('When someone overtakes you','Being overtaken is a cooperation task.', ['Keep as far right as appropriate and do not accelerate.','Do not close a safe gap just because the other driver has made a poor decision.','If the manoeuvre becomes dangerous, reduce risk without sudden or unpredictable movements.'],'Keep right. Hold or reduce speed. Leave room.')])
lesson(17,'Police & emergency vehicles',[124,128],[
card('Know the order of authority','When instructions conflict, use this order: authorised person, traffic lights, traffic signs, general rules.', ['An authorised officer’s instruction takes priority even over a red or green light.','A raised arm means stop for road users, apart from drivers who cannot safely stop and those already in the junction who must clear it.','One or both arms extended horizontally means stop for traffic approaching from directions crossing the indicated line.'],'Person → lights → signs → general rules.','Other authorised people can have limited powers, such as helping children cross. Their permitted instructions must be respected.'),
card('Blue lights and siren','When a priority vehicle announces its approach with its special audible warning, immediately clear a passage, give way and stop if necessary.', ['Check mirrors and move predictably into safe space.','Do not drive into a junction blindly or endanger pedestrians to make room.','Create a rescue corridor early in a queue on roads with multiple lanes in your direction.'],'Make space safely; do not wait for the siren to be beside you.',image='rescue-corridor.webp'),
card('Stay out of the emergency route','An emergency response works best when ordinary drivers stay predictable.', ['Do not follow a priority vehicle through a cleared corridor.','Keep junctions, crossings and access routes free.','Call 112 for a life-threatening emergency; give your location and the nature of the danger.'],'Help by leaving room, not by following.')])
lesson(18,'Traffic lights',[129,139],[
card('Red, amber, green','Traffic lights control entry. A green signal is permission to proceed only when the route is clear and safe.', ['Red: stop before the stop line, or before the signal if there is no line.','Steady amber: stop unless you are so close that you cannot stop safely. Do not speed up to beat it.','Green: proceed, but do not enter a blocked junction or ignore crossing users.'],'Green does not reserve space beyond the junction.'),
card('Flashing amber & arrows','A flashing amber light warns you to be especially careful; other priority rules still apply.', ['When lights are inactive or flashing amber, obey priority signs, then the general priority rules.','A green arrow can allow movement only in its indicated direction; obey the applicable yielding duties.','A small cyclist-only right-turn or straight-on permission does not apply to a car.'],'Flashing amber is caution, not automatic priority.'),
card('Lane signals & railway signals','Signals can close a lane or warn of a train even when the road ahead looks empty.', ['A red cross above a lane means you must not use that lane. A green downward arrow opens it, subject to other rules.','At a railway crossing, stop when red lights flash, the audible warning sounds, or barriers close or are closing.','Never enter a railway crossing unless you can clear it completely.'],'Red railway signal: wait, even if the barrier is still up.',image='level-crossing.webp')])
lesson(19,'Priority signs & roundabouts',[140,152],[
card('Priority road, give way, STOP','These signs change who goes first. Learn the behaviour as well as the shape.', ['Yellow diamond: priority road. Follow its route, including a supplementary diagram if the priority road bends.','Inverted red triangle: give way; stop if necessary.','STOP octagon: come to a complete stop, then give way. Stop at the line, or before entering the junction if no line is marked.'],'Give way may need a stop. STOP always needs one.',image='priority-road-junction.webp'),
card('Shark teeth & stop lines','White triangles mark a give-way position; a solid transverse stop line marks where to stop for STOP or a red signal.', ['Slow before shark teeth and give way to traffic with priority.','At STOP, a rolling slowdown is not a full stop.','Check for a cycle path crossing your approach before you focus on cars on the main road.'],'Look near first: a cycle path may be before the main road.',image='shark-teeth.webp'),
card('A roundabout is a sequence','The give-way signs at a normal roundabout entry give circulating traffic priority.', ['Give way at the entrance. You do not need to indicate just to enter.','Choose and change lanes safely; changing lanes is a manoeuvre and requires giving way.','Indicate right before leaving and check for pedestrians and cyclists crossing your exit.'],'Entry: give way. Exit: signal and check.','Do not infer priority from a circular road alone: look at the actual signs. A driver in an inner lane does not have priority to cut across an outer-lane driver.')])
lesson(20,'Priority from the right',[153,160],[
card('At an equal junction, look right','Without an officer, working lights or priority signs changing the rule, give way to a driver coming from your right.', ['It applies to cars and cyclists. A wider or busier road is not automatically a priority road.','A driver from the right does not lose priority simply because they have stopped.','An unpaved track or path entering a public road is a specific exception; that entering driver must give way.'],'No other instruction? Check right.',image='priority-from-right.webp'),
card('Turning does not remove priority','The direction the driver from the right intends to take does not automatically cancel priority from the right.', ['A vehicle from the right can still have priority when turning toward you or across your route.','Do not rely on eye contact alone. Slow enough to stop if necessary.','Priority from the right does not apply in favour of someone coming from a direction where driving is prohibited.'],'Watch where they come from, then where they are going.',image='priority-from-right-turning.webp'),
card('A manoeuvre must yield','Reversing, leaving a parking space, changing lanes or turning around are manoeuvres.', ['The driver performing a manoeuvre gives way to other road users.','Coming out of private property or a driveway is a manoeuvre, not ordinary priority from the right.','Indicators tell others what you intend; they do not make them give way to you.'],'Manoeuvre = give way to everyone affected.')])
lesson(21,'Turning & positioning',[161,163],[
card('Prepare the turn early','Choose a safe position, reduce speed and signal in good time.', ['For a right turn, approach near the right-hand edge while respecting cycle paths and vulnerable users.','For a left turn on a two-way road, position toward the centre without entering the oncoming side. On a one-way road, position toward the left edge as appropriate.','Check mirrors and blind spots before moving across someone’s line.'],'Plan the turn before the junction.'),
card('Left turn: let oncoming traffic pass','When turning left, give way to oncoming traffic continuing straight or turning right.', ['Do not cut diagonally across the opposing lane.','When two vehicles turn left, follow the prescribed junction layout and pass in the appropriate way.','Wait where you do not obstruct a crossing or block the junction.'],'Turning left usually means waiting for oncoming traffic.'),
card('Protect the crossing route','People continuing along the road may be beside your vehicle rather than directly ahead.', ['Give way to users of the cycle path you cross when turning.','Give way to pedestrians crossing the road you enter or leave.','If your view is blocked by a van or parked car, slow further and check before committing.'],'The final check is beside you, not just in front.')])
lesson(22,'Trains, trams & buses',[164,173],[
card('A railway crossing must stay clear','A train cannot steer around you and needs a long distance to stop.', ['Never enter a crossing if a queue prevents you from clearing the tracks.','Stop for red flashing lights, the audible warning or closing/closed barriers.','If trapped on the tracks, prioritise getting people out and away; call 112 and report the exact crossing.'],'Only enter when your exit is clear.',image='level-crossing.webp'),
card('Trams have special priority','Rail vehicles generally have priority over other road users, even when they come from the left.', ['Police instructions and applicable traffic lights still take precedence.','Do not stop or park on tram tracks.','Be careful near passengers boarding or leaving a tram when there is no protected platform.'],'Tram from the left can still go first.','A tram does not get permission to disregard a red light just because it is on rails.'),
card('Let a bus leave its stop in town','In a built-up area, a bus or trolleybus signalling to leave its stop must be allowed to rejoin traffic.', ['Slow and stop if necessary to let it pull out.','Outside a built-up area, this specific departure-priority rule does not apply; still drive defensively.','Parking is prohibited within 15 metres before and after a bus/tram stop sign, unless the permitted arrangement specifies otherwise.'],'Bus signals out in town? Let it go.',image='bus-stop.webp')])
lesson(23,'Prohibited directions',[174,179],[
card('No entry is not no traffic','A red disc with a horizontal white bar prohibits entry from your direction. A white circle with a red border prohibits traffic in both directions, subject to exceptions.', ['A no-entry sign often marks the wrong end of a one-way road.','Read plates: an exception for cyclists does not include a car.','A forbidden turn sign prohibits the pictured turn. Check whether a separate U-turn prohibition applies.'],'Read your direction and your vehicle category.'),
card('Local traffic & restrictions','Some roads exclude through traffic, certain vehicle types or vehicles over a size or mass limit.', ['Local access can include destinations on the restricted road, but it is not a shortcut permission.','A number for height, width or length includes the load.','Mass restrictions and axle-load restrictions are different; look at the exact symbol.'],'The load counts for a clearance limit.','Do not confuse a sign about actual loaded mass with your licence category, which uses maximum authorised mass.'),
card('One-way does not mean no surprises','A one-way road can have two-way cycling when signs explicitly allow it.', ['Look for exception plates permitting cyclists or mopeds in the opposite direction.','Keep checking both ways at junctions and before opening your door.','A vehicle lawfully approaching from the right under a cycle exception may have priority from the right.'],'One-way for cars can be two-way for cycles.')])
lesson(24,'Mandatory directions',[180,182],[
card('A blue circle tells you what to do','Mandatory-direction signs require the direction or side shown.', ['A straight-ahead arrow requires going straight at the relevant location.','An arrow pointing down and diagonally tells you which side of an obstacle to pass.','A supplementary bicycle or moped exception applies only to the indicated categories.'],'Blue circle: obey the pictured instruction.',image='mandatory-straight.webp'),
card('Combine arrows with lane position','Signs and lane arrows work together. Plan early enough to obey both safely.', ['A directional arrow in your lane determines permitted movements from that lane.','Do not make a sudden prohibited lane change to reach an exit or turn.','If you are in the wrong lane, follow its legal direction and find another route.'],'Wrong lane? Take the safe legal route.',image='lane-arrows.webp'),
card('A route instruction is not priority','Being required to go one way does not tell you who goes first.', ['Continue to obey traffic lights, give-way signs and crossings.','A mandatory turn can still require you to yield to pedestrians or cyclists.','Changing lanes to follow a route remains a manoeuvre.'],'Direction answers “where”; priority answers “when”.')])
lesson(25,'Stopping & parking basics',[183,194],[
card('Stopping is an activity, not a duration','Legally stopping means only the time needed for people to get in or out, or for loading or unloading.', ['Waiting for a friend to arrive is parking, even if you stay in the driver’s seat or leave the engine running.','Waiting at a red light or in traffic is not legal stopping/parking in this sense.','Hazard lights do not change a parked vehicle into a loading stop.'],'Necessary boarding/loading = stopping. Waiting = parking.'),
card('Position the vehicle correctly','Normally stop or park on the right in your direction of travel and as close as possible to the edge.', ['On a one-way road, either side can be allowed.','Use a suitable lawful verge when the rules require it, preserving pedestrian access.','Do not double park, block a cycle path or obstruct a pavement. Keep at least 1.5 m for pedestrians where the verge rule applies.'],'Being “just a minute” does not remove the obstruction.',image='parking-on-cycle-lane.webp'),
card('Places where neither is allowed','Some locations prohibit both stopping and parking because visibility or access is critical.', ['Do not stop or park on crossings, cycle paths, pavements, railway crossings, traffic islands or motorway lanes/shoulders.','On the carriageway, keep at least 5 m before a pedestrian or cycle crossing.','At junctions, keep at least 5 m from the extension of the nearest edge of the crossing carriageway, unless a permitted local arrangement applies.'],'Crossing itself: never. Before it on the carriageway: 5 m.','Further restrictions apply near signs/lights, dangerous bends, hill crests, bridges and tunnels. Do not park where you obscure a signal or create danger.')])
lesson(26,'Parking signs & restrictions',[195,203],[
card('One bar or a cross?','The red-and-blue sign with one diagonal bar prohibits parking. The cross prohibits both stopping and parking.', ['An E1 no-parking sign can still permit genuine loading or boarding if no other rule prohibits stopping.','An E3 no-stopping/no-parking sign prohibits both activities.','The restriction applies on the side of the road where the sign is placed; supplementary plates and zone rules define its extent.'],'One bar = no parking. Cross = no stopping either.',image='no-parking-sign.webp'),
card('Yellow lines, driveways & narrow roads','Parking-only restrictions can apply without a red-and-blue sign.', ['A broken yellow line at the carriageway edge prohibits parking along it.','Do not park where less than 3 m of free carriageway remains, or where you block vehicle access to a property.','Keep the required space around parked vehicles and bus stops. Accessible spaces require a valid parking card displayed and the eligible person’s use.'],'Broken yellow line = no parking.','A property entrance can have a plate-number exception for the identified vehicle. General danger or obstruction rules still apply.',image='yellow-parking-line.webp'),
card('Read the supplementary arrow','A small arrow below a parking restriction tells you which stretch it covers.', ['Arrow up: the restriction starts beyond the sign. Arrow down: the restriction ends at the sign.','Arrows both ways: it applies before and beyond the sign. A distance plate can define the length.','Time windows, vehicle symbols and alternate-half-month rules may limit when or to whom it applies.'],'The main sign tells the rule; the plate tells the scope.','For half-month alternating parking, the changeover on the final day of a period is between 19:30 and 20:00. Check the sign, rather than assuming an odd/even calendar-date rule.',image='no-stopping-sign.webp')])
lesson(27,'Blue zones & leaving the car',[204,210],[
card('Use the parking disc correctly','In a standard blue zone, a parking disc is required on working days, normally Monday to Saturday, between 09:00 and 18:00, unless signs say otherwise.', ['Display the disc clearly behind the windscreen.','Set it to the next half-hour mark following your arrival. For arrival at 10:10, set 10:30.','Normally you may park for 2 hours from the indicated time. A sign can specify a different duration.'],'10:10 arrival → 10:30 on the disc → normally until 12:30.',image='parking-disc.webp'),
card('Do not reset the disc while staying','When your permitted time ends, move the vehicle; merely changing the disc is not allowed.', ['Blue-zone conditions can apply across junctions until the zone end.','A parking-disc plate can also require a disc outside a zone.','Follow local payment instructions. If the parking machine is out of order, the code’s parking-disc rule may apply.'],'Moving the dial is not moving the car.',image='blue-zone.webp'),
card('Check before opening the door','Secure the vehicle, then check for people approaching beside it.', ['Apply the parking brake and secure the car against rolling.','Check mirrors and look over your shoulder before opening a door. Using the opposite hand can help you turn to look.','Do not leave an engine running unnecessarily; lock the car and keep valuables out of sight.'],'A door opening is a road-safety decision.')])
lesson(28,'Alcohol, drugs & fatigue',[211,214],[
card('Know the ordinary alcohol threshold','For ordinary car drivers, the punishable threshold starts at 0.5 g/l in blood (0.5‰) or 0.22 mg/l in exhaled air.', ['A lower threshold applies to certain professional transport drivers.','Alcohol impairs judgement before you feel obviously drunk.','Time lowers alcohol levels; coffee, a shower or fresh air do not make you sober.'],'Safest plan: if you drive, do not drink.',image='breathalyser.webp'),
card('Drugs & medicines count too','Being under the influence of drugs is prohibited. Some legal medicines can also make driving unsafe.', ['Do not assume a prescription guarantees you are fit to drive.','Read warnings and ask a pharmacist about drowsiness, reaction time and interactions with alcohol.','Police can carry out testing under the applicable procedures; refusal is not a way to avoid the rules.'],'Legal to take does not always mean safe to drive.'),
card('Sleep is a safety system','Drowsiness can produce microsleeps: brief lapses during which you are not controlling the road situation.', ['Repeated yawning, drifting position and missing signs are reasons to stop safely.','Opening a window or turning up music is not a reliable fix.','Plan rest breaks, and rest before continuing if sleepy.'],'Stop before your attention stops.','Alcohol-enforcement procedures and licence measures change. This course teaches the driving rules and avoids reproducing the book’s dated penalty tables.')])
lesson(29,'Breakdowns & collisions',[215,224],[
card('Protect the scene first','Avoid creating a second collision. Move to safety when possible and warn approaching road users.', ['Use hazard lights. On a motorway, wear a reflective vest before leaving the car and get behind the barrier when safe.','Place a warning triangle at least 30 m behind on an ordinary road and at least 100 m on a motorway, when it can be done safely.','In a built-up area where the distance is impossible, place it at a smaller distance, potentially on the vehicle, following the code.'],'People first. Visibility second. Paperwork later.',image='warning-triangle.webp'),
card('Injuries: call 112','If anyone is injured, stop, help within your ability, and contact emergency services.', ['Give the exact location, number of casualties and hazards. On a motorway, use direction, exit or kilometre marker.','Do not move an injured person unless immediate danger makes it necessary.','Follow the emergency operator’s instructions. Never put yourself in danger trying to place equipment.'],'112 needs a location and a clear description.','In a tunnel, use the emergency equipment and signed escape routes; do not turn around or reverse to escape a queue.',image='reflective-vest.webp'),
card('After a damage-only collision','Stop and exchange the required identity and vehicle details. Record the facts calmly.', ['Take useful photos if it is safe, including position, damage and signs.','Complete a European accident statement accurately; check the diagram and boxes before signing.','If there is a dispute, refusal to exchange details, injuries or another reason police assistance is needed, contact police.'],'Leaving without the required duties can be a hit-and-run.','Do not stand between vehicles or in a live lane to argue about fault. Insurers assess responsibility using the evidence.')])
lesson(30,'Efficient driving',[225,230],[
card('Smooth driving saves attention and fuel','Look far enough ahead to anticipate slowing traffic rather than repeatedly accelerating and braking.', ['Accelerate smoothly and use a suitable higher gear without labouring the engine.','Ease off early when approaching a red light or queue.','Maintain a steady safe speed and avoid unnecessary idling.'],'Look ahead. Ease off early. Drive smoothly.'),
card('Reduce resistance','The vehicle needs more energy when it pushes extra air or carries unnecessary weight.', ['Remove an unused roof box or carrier.','Use the manufacturer’s correct cold tyre pressures for the load.','Do not carry heavy items unnecessarily; maintain the car regularly.'],'Correct pressure and less roof drag are easy wins.','Do not copy a universal pressure increase from an old book. Use the vehicle’s pressure label and handbook.'),
card('Plan a legal route','A route must be legal for your vehicle as well as convenient.', ['Check local low-emission-zone rules when entering cities; eligibility depends on current local policy and vehicle details.','Combine trips where practical and consider walking, cycling or public transport for short journeys.','Never sacrifice visibility, ventilation or safety to save a little energy.'],'Eco-driving starts with planning, not with risky shortcuts.')])
lesson(31,'Tyres, brakes & assistance',[231,239],[
card('Your tyres are the contact patch','Tyre condition affects grip, braking and control.', ['The minimum tread depth for a normal car tyre is 1.6 mm in the main grooves. Replace worn or damaged tyres in good time.','Check pressure with cold tyres, using the manufacturer’s specification for your load.','Worn tread and standing water increase aquaplaning risk. Reduce speed and avoid abrupt steering or braking if grip is lost.'],'1.6 mm is the legal minimum, not a promise of good wet grip.','The book’s “change tyres every 10,000–15,000 km” should not be treated as a replacement rule. Inspection, wear, age, damage and manufacturer guidance determine maintenance.'),
card('ABS helps you keep steering','ABS prevents sustained wheel lock during heavy braking. You may feel the pedal pulse.', ['In an emergency with ABS, press the brake firmly and maintain pressure while steering as necessary.','Do not pump the pedal as you might have been taught for old non-ABS systems.','ABS does not guarantee a shorter braking distance on every surface.'],'Firm pressure. Keep steering. Do not pump.'),
card('ESP helps, but physics still wins','Electronic stability control helps correct loss of stability by reducing power and braking individual wheels.', ['It cannot create grip that the tyres and road do not have.','Brake, oil-pressure or other serious warnings need the response specified in your handbook; stop safely when required.','Driver assistance never replaces checking mirrors, controlling speed and maintaining space.'],'Assistance supports you; it does not take responsibility.')])
# Verified official source records are supplemented after research integration.
sources=[
 dict(id='code',title='Belgian road code — current consolidated rules',publisher='Wegcode / Vias',url='https://www.wegcode.be/nl/regelgeving/1975120109~hra8v386pu',note='The consolidated 1975 code: priority, manoeuvres, speed, lights, stopping, parking and equipment.'),
 dict(id='exam',title='Theory exam for category B',publisher='Flemish government',url='https://www.vlaanderen.be/rijbewijs-b/theorie-examen-voor-rijbewijs-b',note='Official exam format, pass mark, language support, eligibility and validity.'),
 dict(id='licence',title='Driving licence B',publisher='Flemish government',url='https://www.vlaanderen.be/rijbewijs-b',note='Category B, provisional licences and the learning routes.'),
 dict(id='centres',title='Theory exam at Autoveiligheid',publisher='Autoveiligheid',url='https://www.autoveiligheid.be/rijbewijs/theorie-examen',note='Geel’s exam operator: Dutch screen, Dutch then translated audio, and regular online appointments. Turnhout is listed as an inspection station.'),
 dict(id='newcode',title='Current code and the June 2027 transition',publisher='Wegcode / Vias',url='https://www.wegcode.be/nl/regelgeving/1975120109~hra8v386pu',note='The consolidated current code explicitly states replacement on 1 June 2027 by federal and regional codes.'),
 dict(id='degrees',title='Third- and fourth-degree offences',publisher='Wegcode / Vias',url='https://www.wegcode.be/nl/perma/5yjza0ajqn/regulation_regulation',note='The 30 September 2005 decree classifies offences; the simulator uses it to identify five-point mistakes.'),
 dict(id='geel',title='Geel driving-test centre',publisher='Autoveiligheid',url='https://www.autoveiligheid.be/rijbewijs/examencentra/examencentrum-geel',note='Lammerdries 7, 2440 Geel. Official centre details and appointment links.')]
out=dict(chapters=C,lessons=L,sources=sources,checked='2026-10-01')
(root/'dist/course-content.json').write_text(json.dumps(out,ensure_ascii=False,indent=2))
print('Authored',len(L),'lessons and',sum(len(l['cards']) for l in L),'visual study cards')
