import json
from pathlib import Path
Q=[]
def q(l,text,opts,a,why,nl,nopts,major=False,image=None):
 Q.append(dict(id=f'q{len(Q)+1:03}',lesson=l,text=text,options=opts,answer=a,explanation=why,nl=nl,nlOptions=nopts,major=major,image=image))
q(1,'Which part of a public road is normally used by vehicles?',['The carriageway','Only the pavement','The entire road, without distinction'],0,'The carriageway is the part normally used by vehicles. The public road can also include pavements, cycle paths and verges.','Welk deel van de openbare weg wordt normaal door voertuigen gebruikt?',['De rijbaan','Alleen het trottoir','De volledige weg, zonder onderscheid'],image='road-anatomy.webp')
q(1,'A road is privately owned but open to public traffic. Can road-traffic rules apply?',['Yes','No, never','Only if it has street lights'],0,'Public accessibility matters; private ownership alone does not exclude the road from traffic rules.','Een weg is privé-eigendom maar staat open voor openbaar verkeer. Kunnen de verkeersregels er gelden?',['Ja','Nee, nooit','Alleen als er straatverlichting is'])
q(1,'On an ordinary two-way road, where should you normally drive?',['As far left as possible','As close to the right edge as appropriate','Always astride the centre line'],1,'The normal position is near the right edge, while preserving safe clearance and respecting road markings.','Waar rijd je normaal op een gewone weg met verkeer in beide richtingen?',['Zo ver mogelijk links','Zo dicht mogelijk bij de rechterrand als verantwoord is','Altijd over de middenlijn'])
q(2,'You have a broken white line beside you and a solid line beyond it. May you cross the broken line if the move is safe?',['No, the further line always controls you','Yes, obey the line nearest you','Only after sounding the horn'],1,'With combined solid and broken lines, follow the line nearest your vehicle. You still need a safe, lawful manoeuvre.','Naast jou ligt een onderbroken witte lijn, met daarnaast een doorlopende lijn. Mag je de onderbroken lijn veilig overschrijden?',['Nee, de verste lijn geldt altijd','Ja, de dichtstbijzijnde lijn geldt','Alleen na een claxonsignaal'],image='lane-markings.webp')
q(2,'Very slow traffic approaches a lane closure. Where should drivers use zipper merging?',['Far before the narrowing','Immediately before the narrowing','Only after the lane has already disappeared'],1,'In very slow traffic, merge alternately immediately before the narrowing. This uses the available lanes efficiently.','Bij sterk vertraagd verkeer valt een rijstrook weg. Waar pas je ritsen toe?',['Ver vóór de versmalling','Vlak vóór de versmalling','Pas nadat de rijstrook al verdwenen is'],image='zipper-merge.webp')
q(2,'In roadworks, temporary orange markings conflict with white markings. Which do you follow?',['The white markings','The orange markings','Whichever lane is fastest'],1,'Temporary orange markings take precedence over ordinary white markings.','Bij werken spreken tijdelijke oranje markeringen de witte markeringen tegen. Welke volg je?',['De witte markeringen','De oranje markeringen','De snelste rijstrook'],image='temporary-road-markings.webp')
q(3,'You drive a car in a signed cycle zone. May you overtake a cyclist?',['Yes, with a 1-metre gap','Yes, below 30 km/h','No'],2,'Motor vehicles may not overtake cyclists in a cycle zone. The maximum is 30 km/h.','Je rijdt met een auto in een fietszone. Mag je een fietser inhalen?',['Ja, met één meter afstand','Ja, onder dertig kilometer per uur','Nee'])
q(3,'Does red surfacing alone prove that a strip is a legally reserved cycle path?',['Yes','No, check the signs and markings','Only outside a built-up area'],1,'Colour alone is not the legal definition. A suggested cycle strip can be part of the carriageway.','Bewijst rode verharding op zichzelf dat een strook een voorbehouden fietspad is?',['Ja','Nee, kijk naar borden en markeringen','Alleen buiten de bebouwde kom'])
q(3,'A cyclist is riding along a cycle path that you must cross to turn right. What should you do?',['Turn first because you indicated','Give way to the cyclist','Sound the horn and turn'],1,'When turning across a cycle path, give way to its users. An indicator does not give priority.','Een fietser rijdt op het fietspad dat je kruist om rechts af te slaan. Wat doe je?',['Eerst afslaan omdat je richting aangaf','Voorrang verlenen aan de fietser','Claxonneren en afslaan'])
q(4,'You miss your motorway exit. What is the correct action?',['Reverse along the shoulder','Stop in the exit lane','Continue to the next exit'],2,'Never reverse or turn around on a motorway. Continue to the next exit.','Je mist je afrit op de autosnelweg. Wat doe je?',['Achteruitrijden op de pechstrook','Stoppen in de afritstrook','Doorrijden tot de volgende afrit'])
q(4,'When entering a motorway, who normally has priority?',['Traffic already on the motorway','Traffic in the acceleration lane','The vehicle travelling faster'],0,'The acceleration lane helps you find a safe gap; joining traffic must give way.','Wie heeft normaal voorrang wanneer je een autosnelweg oprijdt?',['Het verkeer dat al op de autosnelweg rijdt','Het verkeer op de invoegstrook','Het snelste voertuig'])
q(4,'A queue forms on a three-lane motorway. Where is the rescue corridor?',['Between the middle and right lanes','Between the leftmost lane and the lane beside it','On the central reservation'],1,'The leftmost lane moves left; every other lane moves right. The corridor is between the leftmost lane and its neighbour.','Er ontstaat een file op een autosnelweg met drie rijstroken. Waar komt de reddingsstrook?',['Tussen de middelste en rechterrijstrook','Tussen de meest linkse rijstrook en de rijstrook ernaast','Op de middenberm'],image='rescue-corridor.webp')
q(5,'In Flanders, you drive a normal car on an ordinary road outside a built-up area. No speed signs apply. What is the normal maximum?',['50 km/h','70 km/h','90 km/h'],1,'The Flemish default on ordinary roads outside a built-up area is 70 km/h. Specific road layouts or signs can change it.','Je rijdt in Vlaanderen met een gewone auto buiten de bebouwde kom op een gewone weg zonder snelheidsborden. Wat is de maximumsnelheid?',['Vijftig kilometer per uur','Zeventig kilometer per uur','Negentig kilometer per uur'],True)
q(5,'Outside a built-up area in Flanders, a road has two lanes each way separated only by paint. No signs apply. May you drive 120 km/h?',['Yes, it has four lanes','No, painted separation is not a physical central reservation','Yes, if traffic is light'],1,'The 120 km/h road-layout exception needs physical separation. In this Flemish painted-separation case, the normal maximum is 70 km/h.','Een weg buiten de bebouwde kom in Vlaanderen heeft twee rijstroken per richting, alleen gescheiden door verf. Zonder borden mag je er honderdtwintig rijden?',['Ja, er zijn vier rijstroken','Nee, verf is geen fysieke middenberm','Ja, bij weinig verkeer'],True)
q(5,'You pass a junction inside a signed 30 km/h zone. Has the zone limit ended?',['Yes, every junction ends it','No, it continues until the zone-end sign','Only if the crossing road is wider'],1,'A zone continues across junctions until its end sign.','Je passeert een kruispunt in een zone dertig. Eindigt de zonelimiet daar?',['Ja, elk kruispunt beëindigt ze','Nee, ze geldt tot het eindezonebord','Alleen als de kruisende weg breder is'],True,image='school-zone.webp')
q(6,'What is the usual maximum for a car in a built-up area in Flanders if no other limit applies?',['30 km/h','50 km/h','70 km/h'],1,'Flanders uses a normal built-up-area maximum of 50 km/h. Brussels generally uses 30 km/h.','Wat is de gewone maximumsnelheid voor een auto binnen de bebouwde kom in Vlaanderen zonder andere beperking?',['Dertig kilometer per uur','Vijftig kilometer per uur','Zeventig kilometer per uur'],True)
q(6,'What is the maximum in a signed residential or home zone?',['20 km/h','30 km/h','50 km/h'],0,'Residential/home zones have a 20 km/h maximum, and pedestrians may use the full road width.','Wat is de maximumsnelheid in een aangeduid erf of woonerf?',['Twintig kilometer per uur','Dertig kilometer per uur','Vijftig kilometer per uur'],True,image='speed-20.webp')
q(6,'Where may you park in a signed residential/home zone?',['Anywhere you leave 3 metres free','Only where markings or signs permit parking','On every pavement'],1,'Parking in a residential/home zone is limited to places indicated by signs or markings.','Waar mag je parkeren in een aangeduid erf of woonerf?',['Overal waar drie meter vrij blijft','Alleen waar borden of markeringen parkeren toelaten','Op elk trottoir'])
q(7,'A pedestrian is clearly about to step onto an unsignalised zebra crossing. What should you do?',['Give way and stop if needed','Continue until they are in your lane','Sound the horn to warn them'],0,'You must give way to pedestrians on or about to use an unsignalised zebra crossing.','Een voetganger wil duidelijk een zebrapad zonder verkeerslichten oversteken. Wat doe je?',['Voorrang verlenen en zo nodig stoppen','Doorrijden tot die in jouw rijstrook staat','Claxonneren om te waarschuwen'])
q(7,'A car has stopped just before an unsignalised zebra crossing. May you overtake it?',['Yes, if you see no pedestrian','No','Yes, below 20 km/h'],1,'The stopped car may hide a pedestrian. Overtaking a vehicle approaching or stopped at such a crossing is prohibited.','Een auto staat stil voor een zebrapad zonder verkeerslichten. Mag je die inhalen?',['Ja, als je geen voetganger ziet','Nee','Ja, onder twintig kilometer per uur'])
q(7,'You turn right into a road a pedestrian is crossing. Who should wait?',['The pedestrian','You must give way','Whoever arrived last'],1,'A turning driver must give way to pedestrians crossing the road being entered.','Je slaat rechts af naar een weg die een voetganger oversteekt. Wie moet wachten?',['De voetganger','Jij moet voorrang verlenen','Wie het laatst aankwam'])
q(8,'May you hold your phone to read a message while waiting at a red light?',['Yes, because the car is not moving','No','Yes, if you keep one hand on the wheel'],1,'Waiting at a red light is still driving. The rule covers holding, using or manipulating an unsecured mobile device with a screen.','Mag je je telefoon vasthouden om een bericht te lezen terwijl je voor rood wacht?',['Ja, de auto beweegt niet','Nee','Ja, met één hand aan het stuur'],True)
q(8,'At an equal junction, a cyclist approaches from your right. Does priority from the right apply to the cyclist?',['Yes','No, only to motor vehicles','Only if the cyclist dismounts'],0,'A cyclist is a driver. Priority from the right is not reserved for cars.','Op een gelijkwaardig kruispunt komt een fietser van rechts. Geldt voorrang van rechts voor die fietser?',['Ja','Nee, alleen voor motorvoertuigen','Alleen als de fietser afstapt'])
q(8,'Someone is walking while pushing a bicycle. How are they treated by the traffic rules?',['As a pedestrian','As a car driver','As a cyclist who must remain on the cycle path'],0,'A person pushing a bicycle is treated as a pedestrian.','Iemand loopt en duwt een fiets voort. Hoe wordt die persoon beschouwd?',['Als voetganger','Als autobestuurder','Als fietser die op het fietspad moet blijven'])
q(9,'What mass normally determines whether a vehicle falls within standard category B?',['Its current empty mass','Its maximum authorised mass','Only the passengers’ combined mass'],1,'Category B generally uses maximum authorised mass, normally up to 3,500 kg, rather than the current empty weight.','Welke massa bepaalt normaal of een voertuig onder een gewoon rijbewijs B valt?',['De huidige lege massa','De maximaal toegelaten massa','Alleen de totale massa van de passagiers'])
q(9,'With a full standard B licence, a trailer has a MAM of 900 kg and the car a MAM of 2,400 kg. Is the combination within the standard B mass rule?',['Yes, total MAM is 3,300 kg','No, every trailer above 750 kg needs BE','No, total MAM exceeds 3,500 kg'],0,'A trailer over 750 kg can be within B when the combination’s MAM does not exceed 3,500 kg. The car’s technical towing limit must also be respected.','Met een definitief rijbewijs B heeft de aanhangwagen een MTM van negenhonderd kilo en de auto vierentwintighonderd kilo. Valt dit binnen de gewone massaregel voor B?',['Ja, samen drieëndertighonderd kilo','Nee, boven zevenhonderdvijftig kilo is altijd BE nodig','Nee, samen meer dan vijfendertighonderd kilo'])
q(9,'Which item belongs in the required equipment of a normal Belgian-registered car?',['A warning triangle','A spare fuel tank','A tow rope in every case'],0,'A warning triangle is required equipment; a normal Belgian car also needs a first-aid kit and an approved fire extinguisher.','Welk voorwerp behoort tot de verplichte uitrusting van een gewone Belgische auto?',['Een gevarendriehoek','Een extra brandstoftank','Altijd een sleepkabel'],image='warning-triangle.webp')
q(10,'A child under 18 is 1.20 metres tall. What is normally required in a car?',['Only an adult seat belt','A suitable child restraint','No restraint in a rear seat'],1,'A child under 18 shorter than 1.35 m normally needs an appropriate child restraint.','Een kind jonger dan achttien is één meter twintig groot. Wat is normaal verplicht in een auto?',['Alleen een volwassenengordel','Een geschikt kinderbeveiligingssysteem','Geen beveiliging achterin'])
q(10,'May a rear-facing child seat be used in front of an active frontal airbag?',['Yes, at low speed','No','Yes, if the child is asleep'],1,'A rear-facing seat must not be used in front of an active frontal airbag. Deactivate it or use a suitable rear-seat position.','Mag een achterwaarts gericht kinderzitje voor een actieve frontale airbag worden gebruikt?',['Ja, bij lage snelheid','Nee','Ja, als het kind slaapt'])
q(10,'May a ladder carried by a passenger car project beyond the front of the car?',['Yes, up to 1 metre','No','Yes, if tied down'],1,'A passenger-car load must not project at the front. Rear projections have separate limits and marking requirements.','Mag een ladder op een personenauto vooraan voorbij de auto uitsteken?',['Ja, tot één meter','Nee','Ja, als ze vastgebonden is'])
q(11,'In fog, visibility is 80 metres. What is required for the rear fog light?',['Use it','Keep it off unless it is night','Use only hazard lights'],0,'Rear fog lights must be used in fog or snowfall with visibility below 100 m, and in heavy rain.','Bij mist is de zichtbaarheid tachtig meter. Wat moet je doen met het mistachterlicht?',['Inschakelen','Uit laten behalve in de nacht','Alleen de alarmlichten gebruiken'])
q(11,'You enter a tunnel during the day. Should you rely on daytime running lights alone?',['Yes, always','No, use proper dipped headlights','Only if the tunnel is busy'],1,'Use dipped headlights in a tunnel. DRLs may not illuminate the rear of your car.','Je rijdt overdag een tunnel in. Volstaan alleen dagrijlichten?',['Ja, altijd','Nee, gebruik de dimlichten','Alleen als het druk is'],image='tunnel.webp')
q(11,'Does indicating before a lane change give you priority?',['Yes','No','Only on a motorway'],1,'An indicator communicates your intention. A lane change is a manoeuvre, and you must give way.','Geeft je richtingaanwijzer je voorrang bij het veranderen van rijstrook?',['Ja','Nee','Alleen op een autosnelweg'])
q(12,'On a motorway, a 90 km/h sign applies. What is the maximum for your normal car?',['120 km/h','90 km/h','130 km/h'],1,'The posted lower limit overrides the normal motorway maximum.','Op de autosnelweg geldt een bord van negentig kilometer per uur. Wat is de maximumsnelheid voor je gewone auto?',['Honderdtwintig kilometer per uur','Negentig kilometer per uur','Honderddertig kilometer per uur'],True)
q(12,'The posted limit is 70 km/h, but dense fog greatly reduces your view. Should you maintain 70?',['Yes, the sign requires it','No, adapt speed to visibility','Yes, with high beam'],1,'A maximum is not a target. You must be able to stop within your visible, clear distance.','De limiet is zeventig maar dichte mist beperkt het zicht. Moet je zeventig blijven rijden?',['Ja, het bord verplicht dat','Nee, pas je snelheid aan het zicht aan','Ja, met grootlichten'])
q(12,'What is the normal speed limit in a built-up area in Brussels when no different limit is signed?',['30 km/h','50 km/h','70 km/h'],0,'Brussels uses 30 km/h in built-up areas. Outside them, ordinary-road and motorway defaults differ.','Wat is de gewone snelheidslimiet binnen de bebouwde kom in Brussel zonder andere limiet?',['Dertig kilometer per uur','Vijftig kilometer per uur','Zeventig kilometer per uur'],True)
q(13,'What makes up stopping distance?',['Only braking distance','Reaction distance plus braking distance','Only the distance travelled in one second'],1,'The car moves during your reaction time, then continues moving while braking. Both distances form the stop.','Waaruit bestaat de stopafstand?',['Alleen de remafstand','Reactieafstand plus remafstand','Alleen de afstand van één seconde'])
q(13,'Under the same grip conditions, doubling speed does what to braking distance approximately?',['Halves it','Doubles it','Quadruples it'],2,'Braking distance grows approximately with the square of speed, so doubling speed roughly quadruples it.','Wat gebeurt ongeveer met de remafstand als je de snelheid verdubbelt bij dezelfde grip?',['Ze halveert','Ze verdubbelt','Ze verviervoudigt'])
q(13,'On a wet road, what should you do with your following gap?',['Increase it','Keep exactly the same gap','Reduce it so nobody merges'],0,'Wet conditions reduce grip and usually increase braking distance, so allow a larger gap.','Wat doe je met je volgafstand op een natte weg?',['Vergroten','Exact gelijk houden','Verkleinen zodat niemand invoegt'])
q(14,'A parked van blocks your side of a narrow two-way road. An oncoming car is close. What should you normally do?',['Go around first','Give way before passing the obstacle','Use the pavement'],1,'When the obstacle is on your side, normally yield to oncoming traffic and go around only when safe.','Een geparkeerde bestelwagen blokkeert jouw kant van een smalle tweerichtingsweg. Er nadert een auto. Wat doe je normaal?',['Eerst voorbijrijden','Voorrang verlenen voor je het obstakel voorbijrijdt','Het trottoir gebruiken'])
q(14,'You have priority at a narrow section, but an oncoming vehicle is already in it. What should you do?',['Enter and force it to reverse','Wait and avoid a collision','Sound the horn continuously'],1,'Priority never removes the obligation to avoid danger. Do not force your way into an occupied narrow section.','Je hebt voorrang aan een versmalling, maar een tegenligger is er al in. Wat doe je?',['Inrijden en hem dwingen achteruit te rijden','Wachten en een aanrijding vermijden','Ononderbroken claxonneren'])
q(14,'To pass an oncoming vehicle, may you force a cyclist onto the verge?',['Yes, if you indicate','No','Only outside town'],1,'You must leave safe clearance and protect vulnerable users. Slow or stop when there is insufficient space.','Mag je een fietser op de berm dwingen om een tegenligger te kruisen?',['Ja, als je richting aangeeft','Nee','Alleen buiten de bebouwde kom'])
q(15,'What is the minimum lateral clearance when passing a cyclist outside a built-up area?',['0.5 metre','1 metre','1.5 metres'],2,'Outside a built-up area, leave at least 1.5 m; within a built-up area, at least 1 m.','Wat is de minimale zijdelingse afstand bij het voorbijrijden van een fietser buiten de bebouwde kom?',['Een halve meter','Eén meter','Anderhalve meter'],image='passing-cyclist.webp')
q(15,'The driver ahead clearly signals and positions to turn left. May you pass on the right if there is enough lawful space?',['Yes','No, there are no exceptions','Only using the cycle path'],0,'This is a specific exception to the normal left-side overtaking rule. The available space must be lawful and safe.','De bestuurder voor je geeft duidelijk links aan en stelt zich op om links af te slaan. Mag je rechts voorbij als er voldoende toegelaten ruimte is?',['Ja','Nee, er bestaan geen uitzonderingen','Alleen via het fietspad'])
q(15,'Before overtaking, you notice another vehicle already overtaking you. What should you do?',['Start anyway','Wait and let it complete its pass','Accelerate to block it'],1,'Check behind before moving left. Do not begin an overtaking manoeuvre when someone is already overtaking you.','Voor je inhaalt zie je dat een ander voertuig jou al inhaalt. Wat doe je?',['Toch beginnen','Wachten en het laten voorbijrijden','Versnellen om het te blokkeren'])
q(16,'May you cross a continuous white line to overtake a slow car?',['Yes, if the road is empty','No','Yes, after flashing your lights'],1,'Crossing a continuous white line to overtake is prohibited. Wait for a legal opportunity.','Mag je een doorlopende witte lijn overschrijden om een trage auto in te halen?',['Ja, als de weg leeg is','Nee','Ja, na een lichtsignaal'],True)
q(16,'Someone is overtaking your car. May you accelerate?',['Yes, to finish sooner','No','Only if they are too slow'],1,'A driver being overtaken must keep right as appropriate and must not accelerate.','Iemand haalt je auto in. Mag je versnellen?',['Ja, om sneller klaar te zijn','Nee','Alleen als die te traag is'])
q(16,'You cannot see beyond a blind bend on an ordinary two-way road. Should you start overtaking a car?',['Yes, quickly','No','Yes, with the horn'],1,'You need sufficient visibility and space to complete a safe overtake. A blind bend removes that assurance.','Je ziet niet voorbij een onoverzichtelijke bocht op een gewone tweerichtingsweg. Begin je een auto in te halen?',['Ja, snel','Nee','Ja, met de claxon'])
q(17,'A police officer instructs you to proceed, but the traffic light is red. Which instruction takes priority?',['The traffic light','The officer’s instruction','The nearest road sign'],1,'An authorised person’s instruction takes precedence over traffic lights, signs and general rules.','Een politieagent beveelt door te rijden maar het verkeerslicht is rood. Wat heeft voorrang?',['Het verkeerslicht','Het bevel van de agent','Het dichtstbijzijnde verkeersbord'])
q(17,'A priority vehicle approaches with its special audible warning. What must you do?',['Immediately clear a safe passage and give way','Keep going unless it touches your lane','Follow closely behind it'],0,'Make passage immediately, give way and stop if necessary, without creating new danger.','Een prioritair voertuig nadert met zijn speciaal geluidssignaal. Wat moet je doen?',['Meteen veilig ruimte maken en voorrang verlenen','Doorrijden tenzij het jouw rijstrook raakt','Er vlak achter rijden'])
q(17,'May you follow an ambulance through a rescue corridor to avoid the queue?',['Yes, if you leave a gap','No','Only with hazard lights'],1,'The rescue corridor is for emergency access, not an extra passing lane.','Mag je achter een ambulance door de reddingsstrook rijden om de file te vermijden?',['Ja, met afstand','Nee','Alleen met alarmlichten'],image='rescue-corridor.webp')
q(18,'A steady amber light appears and you can stop safely before the line. What should you do?',['Stop','Accelerate','Continue because amber always allows passage'],0,'Stop for steady amber unless you are too close to stop safely.','Het licht wordt vast oranje en je kunt veilig voor de streep stoppen. Wat doe je?',['Stoppen','Versnellen','Doorrijden want oranje laat altijd doorgang toe'])
q(18,'You face a red traffic light. May you cross the stop line because the junction looks empty?',['Yes','No','Only late at night'],1,'A red light prohibits passing the stop line. An apparently empty junction does not change it.','Het verkeerslicht is rood. Mag je de stopstreep voorbij omdat het kruispunt leeg lijkt?',['Ja','Nee','Alleen laat in de nacht'],True)
q(18,'The lights at a junction flash amber. Give-way signs are present. Which rule applies?',['The signs, with extra caution','You automatically have priority','The largest vehicle goes first'],0,'Flashing amber warns you to be careful. Priority signs still apply.','De verkeerslichten knipperen oranje en er staan voorrangsborden. Welke regel geldt?',['De borden, met extra voorzichtigheid','Je hebt automatisch voorrang','Het grootste voertuig gaat eerst'])
q(19,'At a STOP sign, no traffic is visible. Must you still come to a complete stop?',['Yes','No, slowing down is enough','Only if a pedestrian is present'],0,'STOP requires a complete stop, then giving way. This differs from a give-way sign.','Aan een STOP-bord is geen verkeer te zien. Moet je volledig stoppen?',['Ja','Nee, vertragen volstaat','Alleen als er een voetganger is'],image='stop-junction.webp')
q(19,'What does this yellow diamond sign indicate?',['End of all speed restrictions','A priority road','A compulsory left turn'],1,'The yellow diamond identifies a priority road. It does not set a speed limit.','Wat betekent dit gele ruitvormige bord?',['Einde van alle snelheidsbeperkingen','Een voorrangsweg','Verplicht links afslaan'],image='priority-road-sign.webp')
q(19,'You leave a roundabout. Which indicator should you use?',['Right','Left','None in every case'],0,'Indicate right before exiting and check for pedestrians and cyclists.','Je verlaat een rotonde. Welke richtingaanwijzer gebruik je?',['Rechts','Links','Nooit een richtingaanwijzer'])
q(20,'In this diagram, there are no signals or priority signs. You drive the purple car. Who normally goes first?',['The purple car','The red car coming from the right','The larger car'],1,'The red car approaches from the purple driver’s right. Priority from the right applies.','Er zijn geen lichten of voorrangsborden. Jij rijdt met de paarse auto. Wie gaat normaal eerst?',['De paarse auto','De rode auto die van rechts komt','De grootste auto'],image='priority-from-right.webp')
q(20,'At an equal junction, a driver from your right has stopped. Have they automatically lost priority?',['Yes','No','Only if stopped for 3 seconds'],1,'Stopping does not automatically remove priority from the right. Do not assume their hesitation gives you priority.','Op een gelijkwaardig kruispunt is de bestuurder rechts gestopt. Verliest die automatisch voorrang?',['Ja','Nee','Alleen na drie seconden'])
q(20,'You reverse out of a parking space. Who must you give way to?',['Only cars coming from the right','All other road users affected by your manoeuvre','Nobody if you indicate'],1,'Reversing is a manoeuvre. The driver performing it must give way to other road users.','Je rijdt achteruit uit een parkeerplaats. Aan wie moet je voorrang verlenen?',['Alleen auto’s van rechts','Alle andere weggebruikers die bij je manoeuvre betrokken zijn','Niemand als je richting aangeeft'])
q(21,'You turn left while an oncoming car continues straight. Who should go first?',['You','The oncoming car','Whoever signals first'],1,'A left-turning driver gives way to oncoming traffic continuing straight or turning right.','Je slaat links af terwijl een tegenligger rechtdoor rijdt. Wie gaat eerst?',['Jij','De tegenligger','Wie eerst richting aangeeft'])
q(21,'Before turning right across a cycle path, what check is essential?',['Only the centre mirror','Mirrors and the right blind spot for cyclists','Only the traffic light ahead'],1,'Cyclists can be beside or behind you. Check mirrors and the blind spot, then give way when crossing their path.','Welke controle is essentieel voor je rechts over een fietspad afslaat?',['Alleen de binnenspiegel','Spiegels en de rechterdodehoek voor fietsers','Alleen het verkeerslicht voor je'])
q(21,'On a two-way road, how should you normally prepare for a left turn?',['Move toward the centre without entering the oncoming side','Move to the right pavement','Drive on the oncoming lane early'],0,'Position toward the centre while remaining on your lawful side, signal and give way as required.','Hoe stel je je normaal op voor links afslaan op een tweerichtingsweg?',['Naar het midden zonder de tegenrichting te gebruiken','Naar het rechtertrottoir','Vroeg op de rijstrook van tegenliggers'])
q(22,'A railway signal flashes red but the barrier is still up. May you cross?',['Yes, until the barrier starts moving','No','Yes, if you see no train'],1,'Red flashing signals already require stopping. Do not wait for the barrier to lower.','Het spoorwegsignaal knippert rood maar de slagboom staat nog omhoog. Mag je oversteken?',['Ja, tot de slagboom beweegt','Nee','Ja, als je geen trein ziet'],image='level-crossing.webp')
q(22,'A tram approaches from your left. No officer or traffic light changes the rule. Who normally has priority?',['You, because the tram is on the left','The tram','The faster vehicle'],1,'Rail vehicles normally have priority over other road users, including when approaching from the left.','Een tram komt van links. Geen agent of verkeerslicht wijzigt de regel. Wie heeft normaal voorrang?',['Jij, want de tram komt van links','De tram','Het snelste voertuig'])
q(22,'In a built-up area, a bus signals to leave its stop. What should you do?',['Let it pull out, stopping if needed','Accelerate past before it moves','Ignore it unless it is on your right'],0,'In a built-up area, allow a signalling bus or trolleybus to leave its stop.','Binnen de bebouwde kom geeft een bus richting aan om zijn halte te verlaten. Wat doe je?',['Laten vertrekken en zo nodig stoppen','Versnellen en er nog voorbijrijden','Negeren tenzij hij rechts staat'],image='bus-stop.webp')
q(23,'A no-entry sign has a plate excepting bicycles. May you enter in a car?',['Yes, at cycle speed','No','Yes, if no cyclists are present'],1,'An exception for bicycles does not apply to a car.','Onder een verboden-inrijbord staat een uitzondering voor fietsen. Mag je met een auto inrijden?',['Ja, aan fietssnelheid','Nee','Ja, als er geen fietsers zijn'])
q(23,'A one-way road permits cyclists in the opposite direction. Should you check for them before turning?',['Yes','No, one-way means no oncoming users','Only at night'],0,'A one-way rule for cars can permit contraflow cycling. Read the plates and check for lawful oncoming cyclists.','Een eenrichtingsweg laat fietsers in tegenrichting toe. Moet je daarop letten voor je afslaat?',['Ja','Nee, eenrichtingsverkeer betekent geen tegenliggers','Alleen in de nacht'])
q(23,'A height-limit sign shows 2.5 metres. Your roof load makes the car 2.6 metres high. May you enter?',['Yes, the sign excludes the load','No','Yes, if the load is soft'],1,'Height restrictions include the load. Your total height exceeds the limit.','Een hoogtebeperking is twee meter vijftig. Met daklading is je auto twee meter zestig hoog. Mag je inrijden?',['Ja, de lading telt niet','Nee','Ja, als de lading zacht is'])
q(24,'What must a car do at the pictured mandatory-direction sign?',['Go straight','Turn left if clear','Choose any direction because bicycles are excepted'],0,'The blue arrow requires straight ahead. The supplementary cycle/moped exception does not exempt a car.','Wat moet een auto doen aan dit gebodsbord?',['Rechtdoor rijden','Links afslaan als het vrij is','Elke richting kiezen omdat fietsen uitgezonderd zijn'],image='mandatory-straight.webp')
q(24,'You discover too late that you are in a straight-ahead-only lane. What is safest and legal?',['Turn anyway','Follow the lane and find another route','Reverse to change lanes'],1,'Follow the lawful lane direction rather than making a sudden prohibited move.','Je merkt te laat dat je in een rijstrook uitsluitend voor rechtdoor staat. Wat is veilig en wettig?',['Toch afslaan','De rijstrook volgen en een andere route zoeken','Achteruitrijden om van strook te veranderen'])
q(24,'A sign requires a right turn. Does that give you priority over pedestrians crossing the road you enter?',['Yes','No','Only if you signal'],1,'A mandatory direction does not override the turning driver’s duty to give way to crossing pedestrians.','Een bord verplicht rechts af te slaan. Geeft dat voorrang op voetgangers die de weg oversteken waar je inrijdt?',['Ja','Nee','Alleen met richtingaanwijzer'])
q(25,'You sit in your car waiting for a friend to arrive. Legally, is this stopping for boarding or parking?',['Parking','Stopping, because you stay inside','Neither if the engine runs'],0,'Waiting for someone to arrive is parking. Stopping is only the time necessary for actual boarding or loading.','Je zit in de auto en wacht tot een vriend aankomt. Is dat stilstaan om in te stappen of parkeren?',['Parkeren','Stilstaan, want je blijft binnen','Geen van beide als de motor draait'])
q(25,'May you briefly stop on a cycle path to drop off a passenger?',['Yes, with hazard lights','No','Yes, if no cyclist is visible'],1,'Both stopping and parking on a cycle path are prohibited. Hazard lights do not create an exception.','Mag je even op een fietspad stilstaan om iemand af te zetten?',['Ja, met alarmlichten','Nee','Ja, als je geen fietser ziet'],image='parking-on-cycle-lane.webp')
q(25,'On the carriageway, how much distance must you normally leave before a pedestrian crossing when stopping or parking?',['At least 1 metre','At least 5 metres','No distance if your car is small'],1,'Stopping and parking on the carriageway are prohibited within 5 m before the crossing. The crossing itself must always stay clear.','Hoeveel afstand moet je op de rijbaan normaal vóór een zebrapad houden bij stilstaan of parkeren?',['Minstens één meter','Minstens vijf meter','Geen afstand bij een kleine auto'])
q(26,'What does the pictured sign prohibit?',['Parking only','Both stopping and parking','All traffic'],0,'One diagonal red bar prohibits parking. Genuine boarding or loading can be allowed if no other stopping prohibition applies.','Wat verbiedt dit bord?',['Alleen parkeren','Stilstaan en parkeren','Alle verkeer'],image='no-parking-sign.webp')
q(26,'What does this red-and-blue cross sign prohibit?',['Only parking overnight','Both stopping and parking','Only loading goods'],1,'The cross sign prohibits both stopping and parking.','Wat verbiedt dit rood-blauwe bord met een kruis?',['Alleen ’s nachts parkeren','Stilstaan en parkeren','Alleen goederen laden'],image='no-stopping-sign.webp')
q(26,'A broken yellow line runs along the carriageway edge. May you park beside it?',['Yes, if you stay in the car','No','Only for 10 minutes'],1,'A broken yellow edge line prohibits parking along it. It does not automatically prohibit genuine stopping, but other restrictions may apply.','Een gele onderbroken lijn ligt langs de rand van de rijbaan. Mag je ernaast parkeren?',['Ja, als je binnen blijft','Nee','Alleen tien minuten'],image='yellow-parking-line.webp')
q(27,'You arrive at 10:10 in a standard blue zone. What time should you set on the disc?',['10:00','10:30','11:00'],1,'Set the next half-hour mark following arrival: 10:10 becomes 10:30. The normal 2-hour period then runs to 12:30 unless signs differ.','Je komt om tien uur tien aan in een gewone blauwe zone. Op welke tijd zet je de parkeerschijf?',['Tien uur','Tien uur dertig','Elf uur'],image='parking-disc.webp')
q(27,'Your blue-zone parking time has expired. May you reset the disc without moving the car?',['Yes','No','Only once'],1,'You must move the vehicle; resetting the disc while staying is prohibited.','Je parkeertijd in de blauwe zone is verlopen. Mag je de schijf opnieuw instellen zonder de auto te verplaatsen?',['Ja','Nee','Slechts één keer'])
q(27,'In a standard blue zone with no different posted hours, is the disc normally required on Saturday at 11:00?',['Yes','No, Saturday is always excluded','Only after 18:00'],0,'Standard blue-zone hours are working days, normally Monday to Saturday, 09:00–18:00. Check signs for local differences and public holidays.','Is in een gewone blauwe zone zonder afwijkende uren normaal een schijf nodig op zaterdag om elf uur?',['Ja','Nee, zaterdag is altijd uitgesloten','Alleen na achttien uur'],image='blue-zone.webp')
q(28,'For an ordinary car driver, at what blood-alcohol level does the usual punishable threshold begin?',['0.5 g/l','1.0 g/l','1.5 g/l'],0,'The ordinary threshold is 0.5 g/l blood, equivalent to 0.5 per mille, or 0.22 mg/l breath. Some professional drivers have a lower threshold.','Vanaf welk alcoholgehalte in het bloed begint de gewone strafbare grens voor een autobestuurder?',['Nul komma vijf gram per liter','Eén gram per liter','Eén komma vijf gram per liter'],image='breathalyser.webp')
q(28,'Which reliably lowers the amount of alcohol in your body?',['Coffee','A cold shower','Time'],2,'Only time allows your body to eliminate alcohol. Coffee and cold showers do not make you sober.','Wat verlaagt betrouwbaar de hoeveelheid alcohol in je lichaam?',['Koffie','Een koude douche','Tijd'])
q(28,'A prescription medicine makes you drowsy. Is it automatically safe to drive because it was prescribed?',['Yes','No','Yes, on short trips'],1,'Prescription status does not guarantee driving fitness. Read warnings and consult a pharmacist.','Een voorgeschreven geneesmiddel maakt je slaperig. Mag je automatisch veilig rijden omdat het is voorgeschreven?',['Ja','Nee','Ja, bij korte ritten'])
q(29,'When safely placing a warning triangle behind a breakdown on a motorway, what is the minimum normal distance?',['10 metres','30 metres','100 metres'],2,'Normally at least 100 m on a motorway, compared with at least 30 m on an ordinary road. Never expose yourself to traffic to place it.','Wat is normaal de minimale afstand voor een veilig geplaatste gevarendriehoek achter een defect voertuig op de autosnelweg?',['Tien meter','Dertig meter','Honderd meter'],image='warning-triangle.webp')
q(29,'There are injured people after a collision. Which emergency number should you call?',['112','Only your insurer','The parking operator'],0,'Call 112, give the exact location, casualties and hazards, and follow the operator’s instructions.','Er zijn gewonden na een ongeval. Welk noodnummer bel je?',['Honderdtwaalf','Alleen je verzekeraar','De parkeerbeheerder'])
q(29,'You break down on a motorway. Where should occupants wait when it is safe to reach it?',['In front of the car','Behind the safety barrier, away from traffic','On the shoulder beside the car'],1,'Get people away from live traffic and behind the barrier when safely possible. Use a reflective vest and warn others without putting yourself at risk.','Je krijgt pech op de autosnelweg. Waar wachten inzittenden als ze er veilig kunnen komen?',['Voor de auto','Achter de vangrail, weg van het verkeer','Op de pechstrook naast de auto'],image='reflective-vest.webp')
q(30,'Which driving style usually reduces fuel use and risk?',['Repeated hard acceleration and braking','Anticipating traffic and easing off early','Tailgating to reduce air resistance'],1,'Anticipation and smooth changes in speed reduce unnecessary acceleration and sudden braking.','Welke rijstijl vermindert meestal verbruik en risico?',['Herhaald hard optrekken en remmen','Vooruitkijken en tijdig gas lossen','Bumperkleven voor minder luchtweerstand'])
q(30,'What should you do with an unused roof box?',['Leave it on permanently','Remove it','Fill it with extra weight'],1,'Removing an unused roof box reduces aerodynamic drag and fuel consumption.','Wat doe je met een dakkoffer die je niet gebruikt?',['Permanent laten staan','Verwijderen','Met extra gewicht vullen'])
q(30,'How should you choose tyre pressure for a loaded trip?',['Use the manufacturer’s cold-pressure specification for the load','Add an arbitrary amount to every car','Use the lowest pressure for comfort'],0,'Use the pressure label or handbook for your actual load, checking cold tyres. A universal pressure increase is not reliable.','Hoe kies je bandenspanning voor een beladen rit?',['De voorgeschreven koude spanning voor die belading','Een willekeurige verhoging voor elke auto','De laagste spanning voor comfort'])
q(31,'What is the legal minimum tread depth in the main grooves of a normal car tyre?',['0.6 mm','1.6 mm','4.0 mm'],1,'The legal minimum is 1.6 mm. More tread can be important for good wet-road performance.','Wat is de wettelijke minimale profieldiepte in de hoofdgroeven van een gewone autoband?',['Nul komma zes millimeter','Eén komma zes millimeter','Vier millimeter'])
q(31,'During emergency braking with ABS, how should you normally use the brake pedal?',['Pump it rapidly','Press firmly and maintain pressure','Release it whenever it pulses'],1,'ABS modulates braking to prevent wheel lock. Maintain firm pressure; pedal pulsation is normal.','Hoe gebruik je het rempedaal normaal bij een noodstop met ABS?',['Snel pompen','Stevig indrukken en druk houden','Loslaten zodra het pulseert'])
q(31,'Does electronic stability control allow you to ignore slippery-road conditions?',['Yes','No','Only with new tyres'],1,'ESP supports stability but cannot create grip or overcome the limits of speed, tyres and road conditions.','Mag je gladde wegen negeren omdat de auto elektronische stabiliteitscontrole heeft?',['Ja','Nee','Alleen met nieuwe banden'])
# Additional visual/scenario questions provide variety beyond the 31 lesson checks.
q(19,'What action do these white triangular markings indicate?',['Give way','Accelerate','Park between the triangles'],0,'Shark teeth mark a give-way position. Check the priority road and vulnerable users before entering.','Welke handeling geven deze witte driehoeken aan?',['Voorrang verlenen','Versnellen','Tussen de driehoeken parkeren'],image='shark-teeth.webp')
q(2,'May you cross the hatched area to reach this motorway exit at the last moment?',['Yes, if you indicate','No','Only if the queue is long'],1,'Hatched areas are not drivable shortcuts. If you miss the legal exit path, continue to the next exit.','Mag je op het laatste moment over het verdrijvingsvlak naar deze afrit rijden?',['Ja, met richtingaanwijzer','Nee','Alleen bij een lange file'],image='motorway-exit.webp')
q(26,'This parking space is reserved for disabled users. Does an ordinary ticket allow you to use it?',['Yes','No, the appropriate valid card and conditions are required','Yes, for five minutes'],1,'Payment alone does not grant use of a reserved accessible space. The eligible person and valid parking card requirements apply.','Deze parkeerplaats is voorbehouden voor personen met een handicap. Mag je er staan met een gewoon parkeerticket?',['Ja','Nee, de geldige kaart en voorwaarden zijn nodig','Ja, vijf minuten'],image='accessible-parking.webp')
q(4,'A car can reach only 60 km/h on level ground. Is it normally admitted to the motorway?',['Yes','No','Only in the right lane'],1,'A vehicle must be capable of reaching 70 km/h on level ground for motorway access. This is an access capability rule, not a queue minimum.','Een auto kan op een vlakke weg maar zestig kilometer per uur halen. Mag die normaal de autosnelweg op?',['Ja','Nee','Alleen op de rechterrijstrook'])
q(12,'What is the normal maximum for a passenger car on a motorway without a lower posted limit?',['90 km/h','120 km/h','130 km/h'],1,'The normal Belgian motorway maximum for an ordinary passenger car is 120 km/h.','Wat is de gewone maximumsnelheid voor een personenauto op een autosnelweg zonder lagere limiet?',['Negentig kilometer per uur','Honderdtwintig kilometer per uur','Honderddertig kilometer per uur'],True)
q(3,'At what point does a signed cycle zone normally end?',['At the next junction','At the end-of-cycle-zone sign','After 100 metres'],1,'Current cycle-zone rules extend across junctions until the zone-end sign. This corrects the book’s older bicycle-street wording.','Waar eindigt een aangeduide fietszone normaal?',['Aan het volgende kruispunt','Aan het einde-fietszonebord','Na honderd meter'])
q(18,'Your light is green but traffic beyond the junction is stationary. May you enter and block the crossing road?',['Yes, because the light is green','No','Only with hazard lights'],1,'Do not enter a junction if you will be stuck blocking it. Green does not remove the duty to keep it clear.','Het licht is groen maar het verkeer voorbij het kruispunt staat stil. Mag je inrijden en de kruisende weg blokkeren?',['Ja, want het is groen','Nee','Alleen met alarmlichten'])
q(11,'It is raining heavily. Are rear fog lights required?',['Yes','No, only fog counts','Only below 30 km/h'],0,'Belgian rules require rear fog lights in heavy rain, as well as fog or snowfall with visibility below 100 m.','Het regent hard. Zijn de mistachterlichten verplicht?',['Ja','Nee, alleen bij mist','Alleen onder dertig kilometer per uur'])
q(15,'In a built-up area, what minimum lateral clearance should you leave when passing a cyclist?',['0.5 metre','1 metre','2.5 metres'],1,'The minimum in a built-up area is 1 m. Leave more if needed; outside it, the minimum is 1.5 m.','Welke minimale zijdelingse afstand houd je bij het voorbijrijden van een fietser binnen de bebouwde kom?',['Een halve meter','Eén meter','Twee en een halve meter'])
q(13,'Which factor increases reaction distance at the same speed?',['A longer reaction time','A brighter paint colour','A lower vehicle roof'],0,'Distraction, fatigue or alcohol can delay your response and increase distance travelled before braking.','Welke factor vergroot de reactieafstand bij dezelfde snelheid?',['Een langere reactietijd','Een fellere lakkleur','Een lager autodak'])
q(20,'You emerge from a private driveway on another driver’s right. Do you automatically have priority?',['Yes','No, leaving a driveway is a manoeuvre','Only if your car is larger'],1,'Leaving a driveway is a manoeuvre. Give way to other road users, rather than claiming priority from the right.','Je komt uit een privé-oprit rechts van een andere bestuurder. Heb je automatisch voorrang?',['Ja','Nee, een oprit verlaten is een manoeuvre','Alleen als je auto groter is'])
q(22,'A queue beyond a railway crossing leaves no room for your car. The signals permit passage. What should you do?',['Enter the tracks and wait','Wait before the crossing until you can clear it','Follow the car ahead closely'],1,'Do not enter unless you can clear the railway crossing completely.','Achter een overweg laat een file geen plaats voor je auto. De signalen laten doorgang toe. Wat doe je?',['Op de sporen rijden en wachten','Voor de overweg wachten tot je er volledig voorbij kunt','Dicht achter de vorige auto rijden'])
# Question-level weighting from the current 30 September 2005 offence-degree decree.
# A question about a maximum permitted speed also costs five points in Flanders.
major_articles = {
'q009':'Turning across cyclists: Article 19.4, third degree',
'q010':'Reversing on a motorway: Article 21.4, fourth degree',
'q019':'Zebra-crossing priority: Article 40.4.2, third degree',
'q020':'Overtaking at a crossing: Article 17.2.5, third degree',
'q021':'Pedestrians when turning: Article 19.5, third degree',
'q022':'Unsecured screen device: Article 8.4, third degree',
'q028':'Child restraint: Article 35.1.1, third degree',
'q029':'Rear-facing seat and active airbag: Article 35.1.1, third degree',
'q040':'Meeting traffic around an obstacle: Article 15.2, third degree',
'q042':'Endangering a cyclist: Article 40ter, third degree',
'q043':'Cyclist lateral clearance: Article 40ter, third degree',
'q046':'Crossing a continuous white line: Article 72.2, third degree',
'q047':'Accelerating while being overtaken: Article 16.7, third degree',
'q048':'Overtaking a car at a blind bend: Article 17.2.3, fourth degree',
'q049':'Authorised person’s instruction: Article 4.1, third degree',
'q050':'Emergency vehicle passage: Article 38, third degree',
'q053':'Passing a red light: Article 61.1.1, third degree',
'q061':'Left-turn priority: Article 19.3.3, third degree',
'q064':'Red railway signal: Article 20.3, fourth degree',
'q067':'No-entry sign C1: Articles 5 and 68.3, third degree',
'q072':'Pedestrians when turning: Article 19.5, third degree',
'q102':'Cyclist lateral clearance: Article 40ter, third degree'
}
for item in Q:
 if item['id'] in major_articles:
  item['major']=True
  item['severityReason']=major_articles[item['id']]
 elif item['major']:
  item['severityReason']='Maximum permitted speed: five-point question under Flemish exam rules'
 else:
  item['severityReason']='Ordinary one-point practice question'
(Path(__file__).resolve().parents[1]/'dist/questions.json').write_text(json.dumps(Q,ensure_ascii=False,indent=2))
print('Authored',len(Q),'bilingual questions,',sum(bool(q['image']) for q in Q),'with images')
